// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINBoGUFT-nngDRVY8jfjsfZLaq0EpndY',
    appId: '1:1088464780143:web:29c41d088dd82cb493c69a',
    messagingSenderId: '1088464780143',
    projectId: 'eventhub-c5d69',
    authDomain: 'eventhub-c5d69.firebaseapp.com',
    storageBucket: 'eventhub-c5d69.appspot.com',
    measurementId: 'G-83QLRQKXZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt4dDOH14a3AoeLy7waUjJ0flLS-i92vc',
    appId: '1:1088464780143:android:3054f3f2599599fc93c69a',
    messagingSenderId: '1088464780143',
    projectId: 'eventhub-c5d69',
    storageBucket: 'eventhub-c5d69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd8npHwcxFsoicJ7lFyWaXD03spJS1uWk',
    appId: '1:1088464780143:ios:23d7caa3c009888493c69a',
    messagingSenderId: '1088464780143',
    projectId: 'eventhub-c5d69',
    storageBucket: 'eventhub-c5d69.appspot.com',
    iosBundleId: 'com.example.eventHub',
  );
}
